version: 0.2  
 
phases:
  install:
    runtime-versions:  
      nodejs: 10
    commands:
      - npm install -g aws-cdk
  pre_build:
    commands:
      - npm i
  build:
    commands:
      - cdk list
      - cdk deploy -v
  post_build:
    commands:
      - echo 'Done'